# Generated by Django 3.2.5 on 2021-07-26 09:55

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('blog', '0005_law_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='law',
            old_name='Category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='law',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='تگ'),
        ),
    ]
