# Generated by Django 3.2.5 on 2021-07-28 08:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210726_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن'),
        ),
    ]
